Astroport Farm
mars-protocol/mars-v2-frontend pull request #1001
Opened 2024-07-15 14:45 UTC by linkielink

This PR enables the Farm UI for the Mars Protocol V2 outpost powered by Astroport Liquidity pools.
It includes
- Fetching and identification of Astroport LP Pool assets
- Listing whitelisted LP Pools in the Farm UI
- Fetching and displaying external incentives
- Deposit & Stake into and Unstake & Withdraw out of Astroport Pools
- Levered LP Farming with LP native tokens (swaping of borrowed tokens doesn't work until a SC update)
- Partial withdraws of staked LP positions
- Displaying staked LP positions as collateral 
- Updated Project dependencies and updated/enabled eslint v8

2024-07-17 08:52 UTC, bobthebuidlr commented on eslint.config.mjs
> +      // ...
```suggestion
```

2024-07-17 12:25 UTC, bobthebuidlr requested changes
My general remarks:

1. Use a separated folder the table/columns for `Vault` and `Farm`. Especially the `Columns` folder is super unorganized and has both common and individual components.

2. 90% of the code lines in folder `Modals/Farm` is a duplicated from `Modals/Vault`. DRY: please create common components 

3. The naming of `Farm` feels confusing and incorrect. Farming is the overarching term for getting yield over your assets. The SC termed it `StakedAstroLp` for a reason. Right now you are using Farm in two different ways: as a general term for any yield strategies AND as the term for staking in LPs. Aside from that you still do refer a lot to either stakedLP and/or LP, which makes it even more confusing to follow along.

2024-07-17 12:25 UTC, bobthebuidlr commented on src/components/earn/farm/Table/Columns/Apy.tsx
This file should then also be renamed  to VaultApy, as it's only used for that

2024-07-17 12:25 UTC, bobthebuidlr commented on src/components/common/TokenInput/index.tsx
> +import DoubleLogo from '../DoubleLogo'
path

2024-07-18 08:53 UTC, linkielink commented on src/store/slices/broadcast.ts
> +            slippage: '0',
Yes, withdrawing liquidity from Astroport doesn't include any slippage. None the less is slippage mandatory for `withdraw_liquidity`

2024-07-18 09:15 UTC, linkielink commented on src/hooks/assets/useAssetsNoOraclePrices.ts
Fetched assets from Astroport can have a price, not an oracle price, but a TWAP price. All assets that have Oracle prices get overwritten by the Oracle prices. All that don't update their price on refetch.

2024-07-18 09:18 UTC, linkielink commented
> My general remarks:
> 
> 1. Use a separated folder the table/columns for `Vault` and `Farm`. Especially the `Columns` folder is super unorganized and has both common and individual components.
> 2. 90% of the code lines in folder `Modals/Farm` is a duplicated from `Modals/Vault`. DRY: please create common components
> 3. The naming of `Farm` feels confusing and incorrect. Farming is the overarching term for getting yield over your assets. The SC termed it `StakedAstroLp` for a reason. Right now you are using Farm in two different ways: as a general term for any yield strategies AND as the term for staking in LPs. Aside from that you still do refer a lot to either stakedLP and/or LP, which makes it even more confusing to follow along.

I renamed and restructured the folders, types and values to represent `astroLp` instead of `farm`.
The `AstroLpModal` is pretty similiar to the `VaultModal`, however I plan on restructuring and refactoring those after the RewardsCenter update. 

Please check if the naming is now less confusing and if the folder structure is better to read

2024-07-22 08:49 UTC, bobthebuidlr approved these changes

2024-07-23 09:57 UTC, merged