feat: added summary when closing an HLS position
mars-protocol/mars-v2-frontend pull request #1012
Opened 2024-07-24 13:33 UTC by linkielink

- Created a `hlsClosingModal` to summarize the actions on closing an HLS position

2024-07-26 08:34 UTC, bobthebuidlr requested changes

2024-07-26 08:34 UTC, bobthebuidlr commented on src/hooks/hls/useDepositHlsVault.ts
> +      ...(borrowAmount.isZero() || !route
I don't think you should do this. If there is no route, we should no allow the actions to be returned and executed at all.

2024-07-26 08:34 UTC, bobthebuidlr commented on src/hooks/hls/useClosePositionActions.ts
> +    const swapExactIn = !routeInfo
Again, I think you should prevent from returning incorrect actions when the information required (`routeInfo`, `swapExactIn`) is not present

2024-07-26 08:34 UTC, bobthebuidlr commented on src/components/Modals/HLS/Close/index.tsx
> +  if (!changes.swap || !changes.repay) return null
You should check for `!changes.swap && !changes.repay`, or allow to show each individually imo. Of course it does not make sense to have a swap OR a repay, but if another error occured and the actions are set wrongly, this could now show incomplete information.

2024-07-26 10:34 UTC, linkielink commented on src/hooks/hls/useDepositHlsVault.ts
> +      ...(borrowAmount.isZero() || !route
The `refund_all_funds` actions should always be present, to not render the Modal unresponsive

2024-07-26 10:37 UTC, linkielink commented on src/hooks/hls/useClosePositionActions.ts
> +    const swapExactIn = !routeInfo
I changed the logic to check if there has to be a swap involved. Without route info, the actions are not part of the actions array. 
We could, however, show an Error Box, telling the user that the swapping route was not able to be fetched. But if that's the case for HLS, we have a bigger problem in the entire app. Maybe an improvement on the app level could be to always check if the SQS or AstroportAPI is responding or not.

2024-07-30 07:46 UTC, linkielink commented on src/hooks/hls/useClosePositionActions.ts
> +    const swapExactIn = !routeInfo
Added a `Callout` if there is debt and no route. I also prevent the Close button to be clickable if there is a route error.

2024-07-30 11:28 UTC, bobthebuidlr approved these changes

2024-07-30 11:34 UTC, merged