Refactor farm
mars-protocol/mars-v2-frontend pull request #1022
Opened 2024-08-01 08:58 UTC by linkielink

refactored farm by merging vault and astroLp components

2024-08-07 16:47 UTC, bobthebuidlr requested changes

2024-08-07 16:47 UTC, bobthebuidlr commented on src/components/Modals/AddFarmAssets/index.tsx
> +  const showContent = modal
Unnecessary to create this variable

2024-08-07 16:47 UTC, bobthebuidlr commented on src/components/account/AccountStrategiesTable/functions.ts
> +        !prev ? primaryAmount : primaryAmount.minus(primaryAmountPrev),
WHy did you add this to the change? If there is no previous, there is no change, so `BN_ZERO` seems correct to me

2024-08-07 16:47 UTC, bobthebuidlr commented on src/components/account/AccountStrategiesTable/functions.ts
> +        !prev ? secondaryAmount : secondaryAmount.minus(secondaryAmountPrev),
Same here of course

2024-08-07 16:47 UTC, bobthebuidlr commented on src/components/account/AccountStrategiesTable/functions.ts
> +        !prev ? primaryAmount : primaryAmount.minus(primaryAmountPrev),
And on these two lines

2024-08-07 16:47 UTC, bobthebuidlr commented on src/hooks/accounts/useUpdatedAccount/functions.ts
> +      console.log(vaultValues[0].address, availableVaults)
log

2024-08-07 16:47 UTC, bobthebuidlr commented on src/hooks/accounts/useUpdatedAccount/functions.ts
> +        status: 'active',
Why don't you spread the current vault anymore to get the metadata? What changed ?

2024-08-08 07:38 UTC, linkielink commented on src/components/account/AccountStrategiesTable/functions.ts
> +        !prev ? primaryAmount : primaryAmount.minus(primaryAmountPrev),
If there is no previous, the position is new and should be green. Like it is for depositing and lending as well.

2024-08-08 07:45 UTC, linkielink commented on src/hooks/accounts/useUpdatedAccount/functions.ts
> +        status: 'active',
This was a type debugging thing, I changed it back.

2024-08-08 07:45 UTC, linkielink commented on src/hooks/accounts/useUpdatedAccount/functions.ts
> +        status: 'active',
This was a type debugging thing, I changed it back.

2024-08-08 08:03 UTC, bobthebuidlr approved these changes

2024-08-08 08:10 UTC, merged