Campaign implementation
mars-protocol/mars-v2-frontend pull request #1031
Opened 2024-08-08 14:16 UTC by linkielink

This PR introduces campaigns for assets, based on the settings inside the `chainConfig`.

An asset can now be flagged as a `campaignAsset` and will show additional info on the UI.
There are two types of campaigns right now; `apy` and `points_with_multiplier`.
The idea is to show additional external protocol rewards based on the campaigns parameter.

This implementation covers:
- underlying auto-compounding Stride APYs
- droplets earned by deposits and farms

Missing implementation due to third party is the updated rewards center, as there is no API to query accumulated Droplets from.

2024-08-08 16:45 UTC, StefChatz requested changes

2024-08-08 16:45 UTC, StefChatz commented on src/components/Modals/Farm/FarmModalContentHeader.tsx
> +    return astroLpPosition.amount.dividedBy(2)
Personal preference but maybe we can shorten this to: 

`return astroLpPosition?.amount.dividedBy(2) || BN_ZERO`

2024-08-08 19:52 UTC, Patricie29 commented
lgtm

2024-08-09 09:04 UTC, bobthebuidlr requested changes

2024-08-09 09:04 UTC, bobthebuidlr commented on src/components/common/assets/AssetCampaignCopy.tsx
> +  const { asset, className, amount, withLogo, size, textClassName } = props
Could be nice to split this up in two components. A Controller where you check for `asset.campaign` and the actual component. Will save some unnecessary renders as well of the hooks that you are now rendering regardless

2024-08-09 09:04 UTC, bobthebuidlr commented on src/components/common/assets/AssetCampaignCopy.tsx
> +  const { asset, className, amount, withLogo, size, textClassName } = props
Or you could also create a type extensions of Asset, like `AssetWithCampaign`. Because you already know that the asset that is passed to this component has the campaign.

2024-08-09 09:04 UTC, bobthebuidlr commented on src/components/Modals/Farm/FarmBorrowings.tsx
> +            max={maxAmount.isNaN() ? BN_ZERO : maxAmount.plus(coin.amount)}
This check seems unnecessary to me. It cannot be NaN. In line 189 you either set amount (BN) or BN_ZERO.

2024-08-09 12:46 UTC, linkielink commented on src/hooks/campaign/useCampaignAprs.tsx
> +      fallback: [] as StakingApr[],
For now, it is. This needs an overhaul if there are other APIs than Stride's in the future. But currently, this way of typing is sufficient. 
This is just a base layer for future campaigns, so I went the route that added the least amount of code.

2024-08-09 12:48 UTC, linkielink commented on src/hooks/assets/useAssetsNoOraclePrices.ts
> +    assetParams && campaignAprs && `chains/${chainConfig.id}/noOraclePrices`,
It's a useless check. You're right. Checking for `campaignsAprs.length` when there are `campaignAssets` is not going to work, as `points_with_multiplier` campaigns have no APRs.

2024-08-09 13:23 UTC, StefChatz approved these changes

2024-08-12 10:53 UTC, merged