Feature/evm usdc fetch
mars-protocol/mars-v2-frontend pull request #1034
Opened 2024-08-11 19:57 UTC by StefChatz

<img width="753" alt="Screenshot 2024-08-11 at 10 54 15 PM" src="https://github.com/user-attachments/assets/bb941eb6-3ee8-4de0-8d13-8429bcb666f5">
<img width="614" alt="Screenshot 2024-08-11 at 10 54 38 PM" src="https://github.com/user-attachments/assets/a5964dfa-ed12-4a18-9922-1e5c449b080a">
<img width="620" alt="Screenshot 2024-08-11 at 10 54 59 PM" src="https://github.com/user-attachments/assets/0c7daded-cebd-4dd2-a568-39961fcf69bc">

This PR builds on the previous EVM wallet connection, and we now can retrieve all EVM USDCC balances (all non-zero addresses will be added very easily once we narrow down our provider) and display them alongside cosmos assets. Furthermore, you can use the slider to select the deposit amount just like you can with previous assets.

2024-08-12 14:55 UTC, linkielink requested changes
This PR is pretty complex, please make sure that depositing is still working on `pion-1` without using EVM assets and also check if `osmosis-1` still works as it did before.

2024-08-12 14:55 UTC, linkielink commented on src/hooks/assets/useUSDCBalances.ts
> +      if (isConnected && address && !isConnecting) {
```suggestion
      if (!isConnected || !address || isConnecting) return
```

2024-08-12 14:55 UTC, linkielink commented on src/hooks/assets/useUSDCBalances.ts
> +  useEffect(() => {
I would wrap the return into a useMemo based on the `isConnecting`, `isConnected` and `address`

2024-08-12 14:55 UTC, linkielink commented on src/types/classes/BNCoin.ts
>      }
I would not hassle with the `BNCoin` object here. 
A better approach (in my opinion) would be to create an object that holds the BNCoin and additional chain information.
Like `WrappedBNCoin` that holds 
```
{
   coin: BNCoin,
   chain: ChainInfoID
}
```

`BNCoin` is the heart of the dApps logic. It is crucial to transactions, and any adjustments or enhancements in its values/keys could lead to transaction failures.

2024-08-12 14:55 UTC, linkielink commented on src/utils/fetchUSDCBalance.ts
> +  [mainnet.id]: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', // Ethereum USDC
I think the mainnet is too slow, but I could be wrong here. It would be interesting to get a test on how fast bridging is. The block time on neutron is between 2 and 5 seconds. If a bridging transaction takes longer than 10 seconds, we need to think about a way around this or "delist" the chain that takes too long to confirm the bridging transaction.

2024-08-15 10:23 UTC, linkielink requested changes

2024-08-15 10:23 UTC, linkielink commented on src/hooks/assets/useUSDCBalances.ts
> +              amount: (Number(balance) * 10 ** 6).toString(),
this will cause issues on higher amounts, as `Number` has a very limited number range.
Please use `WrappedBNCoin.fromBigNumberAndDenom` and convert `balance` with the BigNumber `shiftedBy()` function.

The whole reason we use `BNCoin` is to avoid number range overflows. So please make sure never to use `number` for any coin amount calculations/conversions.

2024-08-15 10:26 UTC, StefChatz commented on src/hooks/assets/useUSDCBalances.ts
> +              amount: (Number(balance) * 10 ** 6).toString(),
Noted!

2024-08-19 11:56 UTC, linkielink approved these changes

2024-08-19 11:56 UTC, merged