Multi Campaign Support
mars-protocol/mars-v2-frontend pull request #1064
Opened 2024-08-22 14:57 UTC by linkielink

This PR adds multi campaign support for assets

2024-08-22 21:35 UTC, StefChatz requested changes

2024-08-22 21:35 UTC, StefChatz commented on src/components/Modals/AssetAmountSelectActionModal.tsx
> +        : null}
```suggestion
      {showCampaignHeader && asset.campaigns
        && asset.campaigns.map((campaign, index) => {
            if (campaign.type === 'points_with_multiplier')
              return (
                <div
                  className={classNames(
                    'w-full p-2 flex items-center justify-center',
                    campaign?.bgClassNames ?? 'bg-white/50',
                  )}
                  key={index}
                >
                  <AssetCampaignCopy
                    campaign={campaign}
                    asset={asset}
                    textClassName='text-white'
                    size='sm'
                    amount={updatedAmount}
                    withLogo
                  />
                </div>
              )
            return null
          })
        }
```

2024-08-22 21:35 UTC, StefChatz commented on src/components/Modals/AssetsSelect/index.tsx
> +        asset.campaigns = isBorrow ? undefined : asset.campaigns
```suggestion
        asset.campaigns = isBorrow || asset.campaigns
```

2024-08-22 21:35 UTC, StefChatz commented on src/components/Modals/Farm/FarmModalContentHeader.tsx
> +        : null}
```suggestion
      {showCampaignHeader && poolToken.campaigns
        && poolToken.campaigns.map((campaign, index) => {
            if (campaign.type === 'points_with_multiplier')
              return (
                <div
                  className={classNames(
                    'w-full p-2 flex items-center justify-center',
                    campaign?.bgClassNames ?? 'bg-white/50',
                  )}
                  key={index}
                >
                  <AssetCampaignCopy
                    asset={poolToken}
                    textClassName='text-white'
                    size='sm'
                    campaign={campaign}
                    amount={updatedDepositedValue}
                    withLogo
                  />
                </div>
              )
            return null
          })
        }
```

2024-08-22 21:35 UTC, StefChatz commented on src/components/account/AccountFund/AccountFundRow.tsx
> +        : null}
```suggestion
      {asset.campaigns && asset.campaigns.length >= 1
        && asset.campaigns.map((campaign, index) => (
            <div className='flex justify-center w-full p-2 mt-4 border rounded border-white/20'>
              <AssetCampaignCopy
                campaign={campaign}
                asset={asset}
                size='sm'
                amount={props.amount}
                withLogo
                className='justify-center'
                key={index}
              />
            </div>
          ))
        }
```

2024-08-22 21:35 UTC, StefChatz commented on src/components/earn/farm/common/Table/Columns/Name.tsx
> +            : null}
```suggestion
          {poolAsset?.campaigns && poolAsset.campaigns.length >= 1
            && poolAsset.campaigns.map((campaign, index) => (
                <AssetCampaignCopy
                  asset={poolAsset}
                  campaign={campaign}
                  size='xs'
                  amount={lpAmount.isZero() ? undefined : lpAmount}
                  key={index}
                />
              ))
            }
```

2024-08-22 21:35 UTC, StefChatz commented on src/components/earn/lend/Table/Columns/Name.tsx
> +            : asset.name
Is it best practice to have double ternary operations?

2024-08-23 06:59 UTC, linkielink commented
Note to myself: never create a hasted PR again.

2024-08-23 10:04 UTC, StefChatz approved these changes

2024-08-23 12:40 UTC, merged