Managed vaults
mars-protocol/mars-v2-frontend pull request #1103
Opened 2024-09-04 11:19 UTC by Patricie29

This PR introduces: 
- a first demo of the new page for Official and Community vaults 
- table with demo data for both official and community vaults 
- info and warning modal when creating/depositing into community vault 

https://github.com/user-attachments/assets/142c28b2-247e-434e-8e5c-d3d3ea688947

2024-09-04 12:40 UTC, linkielink requested changes
Please also add the yellow "You're entering dangerous teritory" dialog that shows up, whenever a user enters the `vaults-community` page.

2024-09-04 12:40 UTC, linkielink commented on src/components/common/Intro.tsx
> +      )
Group the cases
```
    case 'borrow':
      return (
        <div className='absolute top-0 right-0 block w-140 opacity-5'>
          <GridHole />
        </div>
      )
    case 'lend':
    case 'vaults-official':
      return (
        <div className='absolute top-0 right-0 block w-180 opacity-5'>
          <GridTire />
        </div>
      )
    case 'farm':
    case 'vaults-community':
      return (
        <div className='absolute top-0 right-0 block w-140 opacity-5'>
          <GridLandscape />
        </div>
      )
    case 'hls-farm':
      return (
        <div className='absolute bottom-0 right-0 block w-140 opacity-10'>
          <GridWeb />
        </div>
      )
    case 'hls-staking':
      return (
        <div className='absolute top-0 right-0 block w-110 opacity-10'>
          <GridPlanet />
        </div>
      )
```

2024-09-04 12:40 UTC, linkielink commented on src/components/header/navigation/Routes.tsx
> +        <Route path='/vaults-official' element={<VaultsOfficialPage />} />
`vaults-official` should be `vaults`

The `vaults-community` is just an overview page. 

The final URLS should be:
`vaults`
`vaults/create`
`vaults/{VAULT_ADDRESS}`
`vaults/{VAULT_ADDRESS}/mint-account`
`vaults/{VAULT_ADDRESS}/delete`
etc...

2024-09-05 07:42 UTC, linkielink commented
This PR was done in the managed-vaults branch.
For future work, please create branches based on the managed-vaults branch and then do PRs for the managed-vaults branch. This PR will be closed, as it won't be merged into main or develop until Managed Vaults are feature complete.

2024-09-05 07:42 UTC, closed without merging

2024-09-05 07:45 UTC, Patricie29 commented
yep, will do. I actually thought this might not be the correct approach. @linkielink