feature: add styling for non-whitelisted balances
mars-protocol/mars-v2-frontend pull request #1119
Opened 2024-09-10 14:55 UTC by StefChatz

![photo_2024-09-10 17 52 48](https://github.com/user-attachments/assets/30846902-e0e8-435f-a914-cb7fb5aa6543)
![photo_2024-09-10 17 53 03](https://github.com/user-attachments/assets/8e018d75-bc2a-4fa7-8c2e-5e4afd336b7b)

Enhanced AccountBalancesTable to visually distinguish and sort non-whitelisted assets, improving user understanding of collateral status in the account balances view using the tooltip of type info component.

2024-09-10 17:52 UTC, linkielink requested changes
I think a hook `useWhitelistedAsset(denom: string):boolean` would be a good addition. It could work like `useAsset(denom: string):Asset`.

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +        </Tooltip>
```suggestion
        <Tooltip
          type='info'
          content="This asset is not whitelisted and doesn't count as collateral"
          className='cursor-help'
        >
          {content}
        </Tooltip>
```

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +    const isWhitelisted = (denom: string) => whitelistedAssets.find(byDenom(denom)) !== undefined
```suggestion
    const asset = useAsset(row.original.denom)
    const isWhitelisted = !!asset?.isWhitelisted
```

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +      if (isWhitelisted(denom)) return content
```suggestion
    const wrapWithTooltip = (content: React.ReactNode, isWhitelisted: boolean) => {
      if (isWhitelisted) return content
```

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +    )
```suggestion
    const applyRowStyling = (children: React.ReactNode, isWhitelisted: boolean) => (
      <div
        className={classNames('flex items-center', !isWhitelisted && 'opacity-80 hover:opacity-100')}
      >
        {children}
      </div>
    )
```

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +          ),
```suggestion
        cell: ({ row }) =>
          wrapWithTooltip(
            applyRowStyling(
              <Asset type={row.original.type} symbol={row.original.symbol} />,
              isWhitelisted,
            ),
            isWhitelisted,
          ),
```

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +          ),
```suggestion
          wrapWithTooltip(
            applyRowStyling(
              <Value
                amountChange={row.original.amountChange}
                value={row.original.value}
                type={row.original.type}
              />,
              isWhitelisted,
            ),
            isWhitelisted,
          ),
```

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +          ),
```suggestion
              <Size
                size={row.original.size}
                amountChange={row.original.amountChange}
                denom={row.original.denom}
                type={row.original.type}
              />,
              isWhitelisted,
            ),
            isWhitelisted,
          ),
```

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +                ),
```suggestion
                wrapWithTooltip(
                  applyRowStyling(
                    <Price
                      type={row.original.type}
                      amount={row.original.amount.toNumber()}
                      denom={row.original.denom}
                    />,
                    isWhitelisted,
                  ),
                  isWhitelisted,
                ),
```

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +                  row.original.denom,
```suggestion
                    <LiqPrice
                      denom={row.original.denom}
                      computeLiquidationPrice={computeLiquidationPrice}
                      type={row.original.type}
                      amount={row.original.amount.toNumber()}
                      account={updatedAccount ?? account}
                      isWhitelisted={isWhitelisted}
                    />,
                    isWhitelisted,
                  ),
                  isWhitelisted,
```

2024-09-10 17:52 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +          ),
```suggestion
        cell: ({ row }) =>
          wrapWithTooltip(
            applyRowStyling(
              <Apy
                apy={row.original.apy}
                markets={markets}
                denom={row.original.denom}
                type={row.original.type}
              />,
              isWhitelisted,
            ),
            isWhitelisted,
          ),
```

2024-09-10 17:52 UTC, linkielink commented on src/components/common/Table/Row.tsx
> +          !isWhitelisted && 'opacity-50 hover:opacity-100',
What is `applyRowStyling` needed for if you also style the row here?

2024-09-10 18:05 UTC, StefChatz commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +        </Tooltip>
the info type already adds cursor-help so no point adding it

2024-09-10 18:10 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +        </Tooltip>
You can remove the wrapper `<div className='cursor-help'>{content}</div>` then

2024-09-10 18:16 UTC, StefChatz commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +    const isWhitelisted = (denom: string) => whitelistedAssets.find(byDenom(denom)) !== undefined
we are already in a useMemo hook so we can't call this

2024-09-10 18:55 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +    const isWhitelisted = (denom: string) => whitelistedAssets.find(byDenom(denom)) !== undefined
Then move it outside of the useMemo

2024-09-11 06:43 UTC, linkielink approved these changes

2024-09-11 07:02 UTC, linkielink requested changes

2024-09-11 07:02 UTC, linkielink commented on src/components/account/AccountBalancesTable/Columns/useAccountBalancesColumns.tsx
> +          !isWhitelisted && 'opacity-70 hover:opacity-100',
Could you please work with a `group-hover` but with individual columns hover here?
Maybe it makes more sense to move the styling and hover to the Row level. The current implementation doesn't feel like you're hovering the whole row but is pretty column specific.

2024-09-11 11:30 UTC, linkielink requested changes
Please use the specified group to avoid issues when others are using `group` as well.

2024-09-11 11:30 UTC, linkielink commented on src/components/common/Table/Row.tsx
> +          'group',
```suggestion
          'group/assetRow',
```

2024-09-11 11:30 UTC, linkielink commented on src/components/common/Table/Row.tsx
> +                !isWhitelisted && 'group-hover:opacity-100',
```suggestion
                !isWhitelisted && 'group-hover/assetRow:opacity-100',
```

2024-09-11 11:30 UTC, linkielink commented on src/components/common/Table/Row.tsx
> +                !isWhitelisted && 'opacity-70',
```suggestion
                !isWhitelisted && 'opacity-60',
```

2024-09-11 11:31 UTC, linkielink commented on src/components/common/Table/Row.tsx
> +                !isWhitelisted && 'opacity-70',
I feel it looks a bit better if the opacity is lower than `0.7`

2024-09-12 12:25 UTC, linkielink approved these changes

2024-09-12 12:25 UTC, merged