Vault Creation
mars-protocol/mars-v2-frontend pull request #1121
Opened 2024-09-11 14:49 UTC by Patricie29

This PR includes: 
- new gradient colors for vaults page
- hiding credit account selection (working only with wallet)
- whole page overlay for the first step of a vault creation 
- dynamic input component reused for all the forms inputs
- second step for the vault creation - which will include the `vaults_address` in the url

<img width="1170" alt="Screenshot 2024-09-11 at 4 41 49 PM" src="https://github.com/user-attachments/assets/59797d04-c4bf-40c1-af70-43dae162c296">

<img width="778" alt="Screenshot 2024-09-11 at 4 42 56 PM" src="https://github.com/user-attachments/assets/0cc6f3e9-d46c-4447-97c1-2ace683678f9">

<img width="1182" alt="Screenshot 2024-09-11 at 4 43 21 PM" src="https://github.com/user-attachments/assets/a15c8a1d-5c59-46d2-8899-4f6c9e87c9df">

2024-09-15 17:16 UTC, linkielink requested changes
All in all, solid work so far. I would make sure that you don't introduce unnecessary duplicated or new code, so we can reuse components, that you had to create for these UIs in the future.

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/Input.tsx
> +export default function Input(props: Props) {
This Component Name is already taken. `VaultInputElement` would be more suitable.

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/Input.tsx
> +        </button>
Please avoid using vanilla `<button>` components. You can create the button you're showing on `Vault Deposit Asset` with the `Button` component, which has left and right icon settings. It's also currently flat and lacks the border animation because of how it is implemented.

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/Input.tsx
> +          />
Please create a global `<TextArea>` component, that can be reused.
Also disable resizing of the textarea, as this will cause UI issues.

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/Input.tsx
> +  return (
The way you should build the return here would be:

```
return (
    <div className='mt-2'>
      {label && (
        <label className='text-xs flex items-center'>
          {label}
          {required && <span className='text-error ml-1'>*</span>}
        </label>
      )}
      <InputElement type={type} .../>
</div>
```

and then have a function in the same file:

```
function InputElement(props: InputElementProps) {
const { type, ...} = props

if(type === 'button') return (<.../>)
if(type === 'dropdown') return (<.../>)

...

return null
```

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/PerformanceFee.tsx
> +      />
There is a `<NumberInput />` component, that can handle max and min values.

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/index.tsx
> +]
```suggestion
const assets = useWhitelistedAssets()
```

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/index.tsx
> +    navigate(baseUrl)
See comment above on how to generate navigation paths.

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/index.tsx
> +              </Text>
Link to Stargaze (maybe they have a tutorial) and ICNS (maybe this article: https://medium.com/@icns/announcing-icns-the-interchain-name-service-e61e0c3e2abb)

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/index.tsx
> +              $10
```suggestion
              // TODO: fetch from contract
              $10
```
also please use a `<DisplayCurrency />` component here.

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/community/createVault/index.tsx
> +                />
`<TextLink/>` or `<DocsLink/>` component are suitable here

2024-09-15 17:16 UTC, linkielink commented on src/components/vaults/dummyData.ts
You can get the data structure from the SC team already to be prepared for mainnet/testnet data.

2024-09-15 17:16 UTC, linkielink commented on tailwind.config.js
> +        },
Use the `orb` namespace please

2024-09-15 19:24 UTC, Patricie29 commented on src/components/vaults/community/createVault/HLSSwitch.tsx
> +            />
Yes I am.

2024-09-15 20:08 UTC, linkielink commented on src/components/header/navigation/Routes.tsx
> +        <Route path='/vaults/:vaultAddress' element={<CreateVault />}>
That's what I said though.
On the first step you won't have a vault address. AFTER the first step (before minting the credit account) you have the vault address. So it doesn't make much sense to have `vaults/:vaultAddress` as the create page.

2024-09-15 20:46 UTC, Patricie29 commented on src/components/header/navigation/Routes.tsx
> +        <Route path='/vaults/:vaultAddress' element={<CreateVault />}>
ahhh right, I misunderstood

2024-10-11 10:57 UTC, Patricie29 commented on src/components/vaults/community/createVault/AssetSelect.tsx
can I use this tho even if I only want to allow single asset select? @linkielink

2024-10-22 01:06 UTC, Patricie29 commented on src/components/vaults/community/createVault/CreateVaultAccount.tsx
> +          onClick={() => {}}
yep, will add this in vault details pr

2024-10-30 07:24 UTC, linkielink commented
Build is failing with
```
./src/components/vaults/community/createVault/index.tsx:8:23
Type error: Cannot find module 'components/vaults/community/createVault/HlsSwitch' or its corresponding type declarations.
   6 | import VaultInputElement from 'components/vaults/community/createVault/VaultInputElement'
   7 | import PerformanceFee from 'components/vaults/community/createVault/PerformanceFee'
>  8 | import HlsSwitch from 'components/vaults/community/createVault/HlsSwitch'
     |                       ^
   9 | import Text from 'components/common/Text'
  10 | import useToggle from 'hooks/common/useToggle'
  11 | import useStore from 'store'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn build" exited with 1
```

2024-11-19 10:09 UTC, merged