v2.7.1
mars-protocol/mars-v2-frontend pull request #1123
Opened 2024-09-12 12:39 UTC by linkielink

### Accounts
- Non Collateral Assets are now shown less opaque with a tooltip that they are not counting towards collateral

### HLS
- HLS Farm base functions were added to the codebase

### Bugfixes
- The Portfolio Page was showing wrong APRs for HLS accounts

2024-09-12 13:52 UTC, Patricie29 requested changes

2024-09-12 13:52 UTC, Patricie29 commented on src/components/Modals/Farm/FarmModalContent.tsx
> +import HlsFarmingSummary from '../Hls/Deposit/Summary/HlsFarmingSummary'
relative imports

2024-09-12 14:05 UTC, Patricie29 commented on src/components/common/Background.tsx
> +    useStore.setState({ isHls: isHls, isV1: isV1 })
```suggestion
    useStore.setState({ isHls, isV1 })
```

2024-09-12 14:15 UTC, Patricie29 commented on src/components/hls/Farm/Table/Columns/Account.tsx
> +          className=''
can be removed

2024-09-12 15:16 UTC, Patricie29 approved these changes

2024-09-13 07:01 UTC, StefChatz approved these changes

2024-09-13 16:20 UTC, merged