Perps reduce only and SL/TP
mars-protocol/mars-v2-frontend pull request #1170
Opened 2024-10-08 19:57 UTC by StefChatz

2024-10-09 20:08 UTC, linkielink requested changes

2024-10-09 20:08 UTC, linkielink commented on src/components/header/Header.tsx
> +            <NavLink isHome item={{ pages: ['perps'], label: 'home' }}>
```suggestion
            <NavLink isHome item={{ pages: chainConfig.perps ? ['perps'] : ['trade'], label: 'home' }}>
```

2024-10-09 20:08 UTC, linkielink commented on src/components/perps/BalancesTable/Columns/Size.tsx
> +import BigNumber from 'bignumber.js'
BigNumber should be auto-exported by the `app.d.ts`

2024-10-09 20:08 UTC, linkielink commented on src/components/perps/BalancesTable/Columns/Size.tsx
> +import BigNumber from 'bignumber.js'
BigNumber should be auto-exported by the `app.d.ts` there should be no need to import it ever.
`import BigNumber from 'bignumber.js'` can be removed in every tsx file.

2024-10-09 20:08 UTC, linkielink commented on src/components/perps/BalancesTable/index.tsx
> +  console.log('limitOrders', activeLimitOrders)
console.log

2024-10-09 20:08 UTC, linkielink commented on src/components/perps/Module/PerpsModule.tsx
> +            {reduceOnlyWarning && <Callout type={CalloutType.WARNING}>{reduceOnlyWarning}</Callout>}
Also, please move this up and use a labeled Switch component (like Auto-Repay Debt on the Trade Module - same position, same look)

2024-10-09 20:08 UTC, linkielink commented on src/hooks/perps/useSubmitLimitOrder.ts
> +import BigNumber from 'bignumber.js'
make sure to remove all `import BigNumber from 'bignumber.js'` lines from the tsx files

2024-10-09 20:08 UTC, linkielink commented on src/utils/perps.ts
Every `BigNumber()` should be replaced with the `BN()` helper

2024-10-10 15:06 UTC, StefChatz commented on src/components/Modals/AddSLTPModal.tsx
the text-left is needed as by default it is right aligned here

2024-10-10 18:57 UTC, linkielink requested changes

2024-10-10 18:57 UTC, linkielink commented on src/components/perps/Module/PerpsModule.tsx
> +  }, [selectedOrderType])
```suggestion
  useEffect(() => {
      setIsReduceOnly(selectedOrderType === OrderType.STOP)
  }, [selectedOrderType])
```

2024-10-10 18:57 UTC, linkielink commented on src/utils/perps.ts
> +import { BN } from './helpers'
relative import

2024-10-10 19:02 UTC, linkielink requested changes

2024-10-10 19:02 UTC, linkielink commented on src/components/Modals/PerpsSlTpModal.tsx
> +        />
Close the modal on click to have the Toast visible.

2024-10-10 19:05 UTC, linkielink commented
<img width="1266" alt="Screenshot 2024-10-10 at 21 03 37" src="https://github.com/user-attachments/assets/9d903f8b-c03c-422d-84bc-fd8d086c06a7">
Check the de-/magnification on the current/entry prices of limit orders (on setting the fetched limit orders)

2024-10-10 19:06 UTC, linkielink commented
<img width="738" alt="Screenshot 2024-10-10 at 21 03 46" src="https://github.com/user-attachments/assets/2f94785e-cdbb-42f8-b82f-c5b54f4c60cb">
After setting SL/TP it looks like the simulation for the position is still set to it, as it simulates the closing of an open position.

2024-10-10 19:10 UTC, linkielink commented
<img width="358" alt="Screenshot 2024-10-10 at 21 09 21" src="https://github.com/user-attachments/assets/56e39477-20c5-40e2-b79e-e5260eec0b36">
I would not show the Switch on a Long Limit Order if the user has an active Long position open.

This will lead to confusion among users (they get confused easily) ;)

2024-10-11 14:58 UTC, linkielink requested changes

2024-10-11 14:58 UTC, linkielink commented on src/components/perps/BalancesTable/Columns/EntryPrice.tsx
> +          options={{ maxDecimals: 2 }}
Having `entryPrice >= 100 ? 2: 6` is pretty important because it adds additional decimals to prices that are pretty small (smaller than $100). Most perps traders trade fractions of a price, so please add that back.

2024-10-11 15:03 UTC, linkielink approved these changes

2024-10-11 15:03 UTC, merged