Perps
mars-protocol/mars-v2-frontend pull request #1253
Opened 2024-12-05 14:42 UTC by StefChatz

2024-12-05 19:33 UTC, Patricie29 requested changes

2024-12-05 19:33 UTC, Patricie29 commented on src/components/common/Toaster/index.tsx
> +              <div className={`w-4 h-4 ${reduceMotion ? '-mt-2' : '-mt-1'} -ml-1 text-white`}>
Could be chsnged to classNames()

2024-12-05 19:37 UTC, Patricie29 submitted a review, later dismissed

2024-12-05 19:37 UTC, Patricie29 commented on src/hooks/perps/useOpenInterestLeft.ts
> +import usePerpsAsset from './usePerpsAsset'
Relative path

2024-12-06 07:41 UTC, linkielink approved these changes

2024-12-06 08:16 UTC, merged