feat: Flip Direction, Creidt Account Labels, UpdateNotification, Fix PerpsVaultModal unlocking
mars-protocol/mars-v2-frontend pull request #1288
Opened 2024-12-23 15:43 UTC by StefChatz

1. Add AccountLabel component for managing account labels
2. Fix issue with PerpsVaultModal unlock functionality
3. Add Flip Direction option in Manage column of BalancesTable
4. Add UpdateNotification component for displaying update notifications

2024-12-23 16:05 UTC, bobthebuidlr requested changes
The account labels have been a long standing discussion. I'm really not in favor of adding this to the localStorage. It's just too fragile for losses, and also doesn't work across any browser. 

If the user has to "clear local storage" as prompted many times, this information is also lost.

It just feels like a very fragile under-developed feature if we bring it out like this. I'd much rather setup a REDIS instance where the account ids are keyed with the labels.. Think this is up to Dane

2024-12-23 16:05 UTC, bobthebuidlr commented on src/components/common/UpdateNotification.tsx
> +export default function UpdateNotification() {
Did you actually test this? To me it's unclear if it would work.

This hook renders only once, which means only when loading the application. When that is the case, it should already be the newest version. If the user leaves the page open, this hook also shouldn't rerender, which means it never really gets to check again for a newer version.

2024-12-23 16:05 UTC, bobthebuidlr commented on src/components/account/AccountLabel.tsx
> +export default function AccountLabel({ accountId, className }: Props) {
I'm assuming you should also use the account label on all other places in teh application: Portfolio pages, the Credit Manager Expanded etc.

2024-12-25 15:32 UTC, StefChatz commented on src/components/common/UpdateNotification.tsx
> +export default function UpdateNotification() {
Correct, I have made it re-check it every 10 minutes

2025-01-15 08:12 UTC, linkielink requested changes

2025-01-15 08:12 UTC, linkielink commented on src/components/account/AccountBalancesTable/index.tsx
> +import AccountLabel from '../AccountLabel'
relative import

2025-01-21 13:44 UTC, linkielink commented
Closed for now, until internal clarification

2025-01-21 13:44 UTC, closed without merging