Mp 2317 refactor toast messages tx history
mars-protocol/mars-v2-frontend pull request #884
Opened 2024-04-03 11:59 UTC by linkielink

This PR introduces Toast Messages based on the response of the executed transaction

2024-04-03 14:40 UTC, bobthebuidlr requested changes
Overall super nice to see this improvement in details for the Toast messages.

There are a few cases not filled in the `generateToast` method. The whole start of this story was exactly to get the Perps messages, so why aren't these done yet?

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +function getCoinFromEvent(event: TransactionEvent) {
```suggestion
function getCoinsFromEvent(event: TransactionEvent) {
```

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +function getCoinFromEvent(event: TransactionEvent) {
You are returning an array

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +function getTransactionCoins(result: BroadcastResult, address: string, target: string) {
This function is basically impossible to follow along with. Not because it's bad code, but because the event messages of the SC are mixed and messed up. This code is still very prone for bugs, but I don't see any other way than to streamline the event messages from SC to FE.

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +  return BNCoin.fromDenomAndBigNumber(coin1.denom, BN(coin1.amount).plus(BN(coin2.amount))).toCoin()
Why not just return:
```
return {
    denom: coin1.denom,
    amount: BN(coin1.amount).plus(coin2.amount)
}
```

I think it's much more readable and clear what is happening

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/generateToast.ts
> +  switch (transactionType) {
TransactionType should definitely be strong typed into an enum or typed strings

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/generateToast.ts
> +        toast.content.push({
So for NON HLS transactions, the `Deposited from wallet` is not covered?

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/generateToast.ts
> +      if (isHLS && txCoins.deposit.length === 2) {
It's probably better to name `sHLS && txCoins.deposit.length === 2` into a variable with a proper name for clarity + a comment.

2024-04-03 14:40 UTC, bobthebuidlr commented on src/types/interfaces/store/broadcast.d.ts
> +  borrow: Coin[]
Why `Coin` and not `BNCoin` ?

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/generateToast.ts
> +              coins: [{ denom: coin.denom, amount: BN(coin.amount).abs().toString() }],
There is a method on BNCoin: `[coin.abs()]`. You will need to change the types of `txCoins`  to BNCoin of course

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/generateToast.ts
> +        const modification = txCoins.perpsModify[1]
You can also alter this so that the `before` is allowed to be null. With this alteration, you can squash the `perpsOpen` and `perpsModify` in one

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/generateToast.ts
> +        if (BN(modification.amount).isGreaterThan(0)) {
This is a very tough one. You are always assigning `modification` a positive number if it's enlarging the previous TradeDirection, but you are allowing the `before` to be negative. This is very unclear.

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/generateToast.ts
> +        if (BN(modification.amount).isGreaterThan(0)) {
I would suggest implementing my comment above. Then it's more clear

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/generateToast.ts
> +        if (BN(modification.amount).isGreaterThan(0)) {
Wait the logic is flawed overal I see now. It is allowed to be negative. But this allows the message to say `Increased SHORT by` when the short has actually descreased. (as a negative change is an increased short position)

2024-04-03 14:40 UTC, bobthebuidlr commented on src/utils/generateToast.ts
> +    case 'modify-perp':
Aren't you already checking for modifying a perp position in the previous case?

2024-04-03 15:50 UTC, linkielink commented on src/components/Modals/HLS/Deposit/SubTitles.tsx
> +          ) ?? ''
That is correct, but `formatAmountWithSymbol` can return`undefined` but SubTitle doesn't allow `undefined` in its `text` propperty

2024-04-03 15:50 UTC, linkielink commented on src/components/Modals/HLS/Deposit/SubTitles.tsx
> +          ) ?? ''
I rewrote it.

2024-04-03 15:50 UTC, linkielink commented on src/types/interfaces/store/broadcast.d.ts
> +  borrow: Coin[]
Because `BNCoin` can't be stored in the `localStorage` and even if we convert it before hand, the recent transaction history would not be downwards compatible, crashing the app for previous users.

2024-04-03 15:50 UTC, linkielink commented on src/types/interfaces/store/broadcast.d.ts
> +  pnl: Coin[]
What if a different feature has pnl as well? Currently `pnl` only returns `Realised Profit` and `Realised Loss`. If we want to stay modular, we need to keep this as `pnl`

2024-04-03 15:50 UTC, linkielink commented on src/utils/broadcast.ts
> +  /* TODO: beautify error messages */
This would be a new PR. I added the comment, so it doesn't get lost.

2024-04-03 15:50 UTC, linkielink commented on src/utils/generateToast.ts
> +    case 'execution':
`execution` is the fallback if the analize function doesn't find any rule fulfilled it returns `execution` so the toast shows the information

```
Transaction successful
Executed a transaction
```

2024-04-05 07:05 UTC, bobthebuidlr commented on src/utils/vaults.ts
> +export function getVaultByDenoms(chainConfig: ChainConfig, coins: Coin[]) {
```suggestion
export function getVaultByCoins(chainConfig: ChainConfig, coins: Coin[]) {
```

2024-04-05 07:09 UTC, bobthebuidlr commented on src/utils/vaults.ts
> +  const vault = vaults.find((vault) => {
It's a little more effective if you do something like this:
```
const coinDenoms = coins.map((coin) => coin.denom)

return vaults.find((vault) => 
    [vault.denoms.primary, vault.denoms.secondary].every((denom) => coinDenoms.includes(denom))
 )?.name
```

2024-04-05 07:10 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +  // This should be streamlined by SC one day
Nice, these comments really give the right context!

2024-04-05 07:23 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +
paths

2024-04-05 07:24 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +function getTransactionCoins(result: BroadcastResult, address: string, isHLS: boolean) {
```suggestion
function getTransactionCoinsGrouped(result: BroadcastResult, address: string, isHLS: boolean) {
```

2024-04-05 07:34 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +  if (coin1.denom !== coin2.denom) return coin2
This seems like incorrect behaviour to me. I think it should throw an error when this happens, not the coin that you are trying to merge into the first one.

This functions responsibility is just to merge the coins. If there needs to be a denom check, it should be done outside of this function IMO.

2024-04-05 07:36 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +  return BNCoin.fromDenomAndBigNumber(coin1.denom, coin1.amount.plus(coin2.amount))
Might be nice to add a method on the `BNCoin` class for this.

```
plus(amount: BigNumber) {
    return BNCoin.fromDenomAndBigNumber(this.denom, this.amount.plus(amount))
}
```

2024-04-05 07:36 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +  return BNCoin.fromDenomAndBigNumber(coin1.denom, coin1.amount.plus(coin2.amount))
Then you can remove this function overall, and just use:
```
coin1.plus(coin2.amount)
```

2024-04-05 07:47 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +            coin.coin.denom === txCoin.coin.denom && coin.coin.amount.isEqualTo(txCoin.coin.amount),
Subtle suggestion: Perhaps we should revisit the type a just a little. Right now you have to use `coin.coin.amount`, which is a bit unclear. 

Perhaps we should use: `coin.after.amount`

2024-04-05 07:49 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +  coins.forEach((txCoin) => {
This is such a good usecase for a `reduce` function :D Can you rewrite this?

2024-04-05 07:54 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +    case 'perps':
This is quite difficult to read. There are 3 states for perps: `open`, `close` and `modify`. Perhaps we can identify this state in the beginning, and then use a switch statement

2024-04-05 07:54 UTC, bobthebuidlr commented on src/utils/broadcast.ts
> +export function sortFunds(funds: Coin[]) {
What's up with this? Should you fix this on this PR?

2024-04-05 12:46 UTC, merged